package main

import (
	"context"
	"fmt"
	"math/rand"
	"sync"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	ch := make(chan struct{})
	wg := &sync.WaitGroup{}
	for i := 1; i <= 10; i++ {
		wg.Add(1)
		go mineCoin(25, ctx, i, wg, ch)
	}
	<-ch
	close(ch)
	cancel()
	wg.Wait()

}

func mineCoin(num int, ctx context.Context, id int, wg *sync.WaitGroup, ch chan struct{}) {
	defer wg.Done()
	for {
		select {
		case <-ctx.Done():
			fmt.Println("goroutine id:", id, " closing suceesfully")
			return
		default:
			number := rand.Intn(100)
			fmt.Println("number :", number, ", Id:", id)
			if num == number {
				fmt.Println("Number has generated by goroutine :", id)
				ch <- struct{}{}
				return
			}
		}
	}
}
